version: '3.8'
services:
  db:
    image: mysql:8.1
    container_name: fruit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fruitdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - fruit-mysql-data:/var/lib/mysql

volumes:
  fruit-mysql-data:
